### ISSUE TITLE
Publish releases into Gradle Plugin Portal

### ISSUE THREAD

**Issue by rachelcarmena** [47degrees/hood#47]
## Context

This issue comes from a conversation with awesome @AdrianRaFo :raised_hands:  We published a plugin for Arrow Meta in Gradle Plugin Portal though it's not available now because we removed it to wait for a release version.

## Advantages
- Allow to use the released plugin with [the plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) instead of the legacy plugin application.
- Have all the 47 Degrees Gradle Plugins in a page: https://plugins.gradle.org/u/47degci

### 1. Have a Gradle account

@franciscodr created an account for 47Deg: https://plugins.gradle.org/u/47degci That account has a `gradle.publish.key` and `gradle.publish.secret`.

### 2. Create the secrets

* `GRADLE_PUBLISH_KEY`
* `GRADLE_PUBLISH_SECRET`

### 3. Configuration

Configure `plugins`, `gradlePlugin` and `pluginBundle` in `build.gradle`. 

For instance: https://github.com/arrow-kt/arrow-meta/blob/master/gradle-plugin/build.gradle

### 4. Publish the plugin

Step for GitHub actions:

```
- name: Publish Gradle Plugin
  env:
    GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
    GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
  run: |
    ./gradlew -Dgradle.publish.key=$GRADLE_PUBLISH_KEY -Dgradle.publish.secret=$GRADLE_PUBLISH_SECRET publishPlugins
```

The first time, publish action will create a request for The Gradle team. The console output will be something like:
```
Publishing plugin XXX version XXX
Thank you. Your new plugin XXX has been submitted for approval
by Gradle engineers. 
The request should be processed within the next 24 hours, at which point
you will be contacted via email.
```

When it's approved, an email with the subject **[Gradle] Plugin approved** will be received and the plugin will appear in the Portal. And then, all the necessary versions will be able to be published without approval.

## Links
- The guide that I followed: https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/
- Gradle Plugin Portal: https://plugins.gradle.org/
